language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ojaspatharkar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ojaspatharkar/docker-react npm run test